#!/usr/bin/python

import boto3
import sys
import sys


def main(action = help):

  s = boto3.session.Session(profile_name='default')
  ec2 = s.resource('ec2')
  
  if action == "help":
    print "ec2 <stop|list|start|terminate>"

  if action == "stop":
    for i in ec2.instances.all():
      print "stopping the instance.{0}".format(i.tags)
      i.stop()
      print i.state

  if action == "list":
    for i in ec2.instances.all():
      print i.state

  if action == "start":
    print "Don't be lazy pasha. Goto Console and start only required instances"

  if action == "terminate":
    for i in ec2.instances.all():
      prompt = "Are you sure to terminate {0} (y/n)".format(i.tags)
      ans = raw_input(prompt)
      if ans == 'y' or ans == 'Y':
        i.terminate()
        print "done"
      else:
        print "OK.. Skipped {0}".format(i.tags)
    


if __name__ == '__main__':
  if len(sys.argv) > 1:
    main(sys.argv[1])
  else:
    print "provide the action <stop|list|start|terminate|help>"
